#!/bin/dash

sub=$(echo $1 | grep [0-9]:[a-zA-Z0-9_.-]*)

if [ -z $sub ]
then
    file=$(echo $1 | sed -r 's/^://')

    if [ ! -e .shrug/index/$file ]
    then
        echo "shrug-show: error: '$file' not found in index"
    else
        cat .shrug/index/$file
    fi
else
    commit=$(echo $1 | sed -r 's/:[a-zA-Z0-9_.-]*//')
    file=$(echo $1 | sed -r 's/^[0-9]://')

    if [ ! -d ".shrug/$commit-commit/" ]
    then
        echo "shrug-show: error: unknown commit '$commit'"
    elif [ ! -e .shrug/$commit-commit/$file ]
    then
        echo "shrug-show: error: '$file' not found in commit $commit"
    else
        cat .shrug/$commit-commit/$file
    fi
fi


