#!/bin/dash

index_path=".shrug/index"

if [ ! -d ".shrug" ]
then    
    echo ".shrug does not exist"
    exit 1
fi

if [ ! -d "$index_path" ]
then
    echo "index does not exist"
    exit 1
fi

i=0
while [ -d ".shrug/$i-commit" ]
do 
    i=$(($i + 1))
done 

if [ $i -ne 0 ] && [ "$1" != "-a" ]
then
    i=$(($i - 1))

    difference=0
    if [ -z "$(ls .shrug/index)" ] && [ -z "$(ls .shrug/$i-commit)" ]
    then
        echo "nothing to commit"
        exit 1
    elif [ -z "$(ls .shrug/index)" ] 
    then
        difference=1
        continue
    fi

    for file in .shrug/index/*
    do
        new_file=$(echo $file | sed -r 's/^.shrug\/index\///')
        if [ ! -f ".shrug/$i-commit/$new_file" ]
        then
            difference=1
            continue
        else
            cmp -s ".shrug/index/$new_file" ".shrug/$i-commit/$new_file"
            index_commit=$?
            if [ $index_commit -ne 0 ]
            then
                difference=1
                continue
            fi
        fi
    done

    for file in .shrug/$i-commit/*
    do
        new_file=$(echo $file | sed -r 's/^.shrug\/[0-9]+-commit\///')
        if [ ! -e .shrug/index/$new_file ] && [ "$new_file" != "message.txt" ]
        then
            difference=1
            continue
        fi
    done

    if [ $difference -eq 0 ]
    then
        echo "nothing to commit"
        exit 1
    fi
    i=$(($i + 1))
fi

# -a option
if [ "$1" = "-a" ]
then
    for file in .shrug/index/*
    do
        filename=$(echo $file | sed -r 's/^.shrug\/index\///')
        if [ -f $filename ]
        then
            cp "$filename" "$file"
        fi
    done
fi

touch ".message.txt"
message=""
for text in $@
do
    message="$message $text"
done

echo "$message" | sed -r 's/^(-a)? -m//' | sed -r 's/^ *//g' > ".message.txt"

mkdir ".shrug/$i-commit"
commit="$i-commit"

mv ".message.txt" ".shrug/$commit"

echo "Committed as commit $i"

for file in .shrug/index/*
do
    if [ ! -f $file ]
    then    
        continue
    fi
    cp "$file" ".shrug/$commit"
done


echo -n "" > .shrug/.last_action.txt




