#!/bin/dash

if [ ! -d ".shrug" ]
then    
    echo "shrug-add: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

. .shrug/path

if [ ! -d "$branch_path/index" ]
then
    mkdir "index"
    mv "index" "$branch_path"
fi

for file in $@
do
    if [ ! -e "$file" ]
    then
        if [ -e $branch_path/index/$file ]
        then
            rm $branch_path/index/$file
        else
            echo "shrug-add: error: can not open '$file'"
        fi
        continue
    elif test "$file" != "^[a-zA-Z0-9][a-zA-Z0-9.-_]+$"
    then
        cp "$file" "$branch_path/index"
    else
        echo "$file is an invalid file"
    fi
done
