#!/bin/dash

if [ ! -d ".shrug" ]
then 
    echo "Initialized empty shrug repository in .shrug"
    mkdir ".shrug"
else
    echo "shrug-init: error: .shrug already exists"
fi

if [ ! -d ".shrug/branch-master" ]
then
    mkdir ".shrug/branch-master"
fi

touch path
echo "#!/bin/sh" > path
printf "\n" >> path
echo "branch_path=\".shrug/branch-master\"" >> path

mv "path" ".shrug"


