#!/bin/dash

if [ ! -d ".shrug" ]
then    
    echo "shrug-commit: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

. .shrug/path

if [ ! -d "$branch_path/index" ]
then
    echo "nothing to commit"
    exit 1
fi

i=0
for file in .shrug/*
do
    while [ -d "$file/$i-commit" ]
    do 
        i=$(($i + 1))
    done 
done

if [ $i -ne 0 ] && [ "$1" != "-a" ]
then
    i=$(($i - 1))

    difference=0
    if [ -z "$(ls $branch_path/index)" ] && [ -z "$(ls $branch_path/$i-commit)" ]
    then
        echo "nothing to commit"
        exit 1
    elif [ -z "$(ls $branch_path/index)" ] 
    then
        difference=1
        continue
    fi

    for file in $branch_path/index/*
    do
        new_file=$(echo $file | sed -r "s|^$branch_path/index/||")
        if [ ! -f "$branch_path/$i-commit/$new_file" ]
        then
            difference=1
            continue
        else
            cmp -s "$branch_path/index/$new_file" "$branch_path/$i-commit/$new_file"
            index_commit=$?
            if [ $index_commit -ne 0 ]
            then
                difference=1
                continue
            fi
        fi
    done

    for file in $branch_path/$i-commit/*
    do
        new_file=$(echo $file | sed -r "s|^$branch_path/[0-9]+-commit/||")
        if [ ! -e "$branch_path/index/$new_file" ] && [ "$new_file" != "message.txt" ]
        then
            difference=1
            continue
        fi
    done

    if [ $difference -eq 0 ]
    then
        echo "nothing to commit"
        exit 1
    fi
    i=$(($i + 1))
fi

# -a option
if [ "$1" = "-a" ]
then
    for file in $branch_path/index/*
    do
        filename=$(echo $file | sed -r "s|^$branch_path/index/||")
        if [ -f $filename ]
        then
            cp "$filename" "$file"
        else
            rm "$file"
        fi
    done
fi

touch ".message.txt"
message=""
for text in $@
do
    message="$message $text"
done

echo "$message" | sed -r 's/^(-a)? -m//' | sed -r 's/^ *//g' > ".message.txt"

mkdir "$branch_path/$i-commit"
commit="$i-commit"

mv ".message.txt" "$branch_path/$commit"

echo "Committed as commit $i"

for file in $branch_path/index/*
do
    if [ ! -f $file ]
    then    
        continue
    fi
    cp "$file" "$branch_path/$commit"
done




