#!/bin/dash

. .shrug/path

if ! echo $1 | grep -q ":"
then
    echo "shrug-show: error: invalid object $1"
    exit 1
fi

sub=$(echo $1 | grep [0-9]:[a-zA-Z0-9_.-]*)

if [ -z $sub ]
then
    file=$(echo $1 | sed -r 's/^://')

    if [ ! -e $branch_path/index/$file ]
    then
        echo "shrug-show: error: '$file' not found in index"
    else
        cat $branch_path/index/$file
    fi
else
    commit=$(echo $1 | sed -r 's/:[a-zA-Z0-9_.-]*//')
    file=$(echo $1 | sed -r 's/^[0-9]://')

    if [ ! -d "$branch_path/$commit-commit/" ]
    then
        echo "shrug-show: error: unknown commit '$commit'"
    elif [ ! -e $branch_path/$commit-commit/$file ]
    then
        echo "shrug-show: error: '$file' not found in commit $commit"
    else
        cat $branch_path/$commit-commit/$file
    fi
fi


